/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to high-level task events
         * @description Server-Sent Events (SSE) endpoint for real-time task updates.
         *
         *     Clients can subscribe to this endpoint to receive notifications when tasks
         *     are created, updated, or deleted. Events are emitted by TaskEventService
         *     directly from TaskService operations, ensuring one event per operation.
         *
         *     **Event Guarantees:**
         *     - One operation = one event (no duplicates from filesystem)
         *     - Events emitted synchronously with task operations
         *     - Events include the full task object - no follow-up API calls needed
         *     - For updates, includes detailed change information
         *
         *     **Event Types:**
         *     - `task.created`: New task created - includes the complete task
         *     - `task.updated`: Task modified - includes full task + changes object
         *     - `task.deleted`: Task deleted - includes the task's last known state
         *
         *     **Recommended for:** Frontend UI updates
         *
         *     Connection stays open indefinitely. Clients should implement reconnection logic.
         */
        get: operations["subscribeToTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to low-level file system events
         * @description Server-Sent Events (SSE) endpoint for filesystem-level events.
         *
         *     This endpoint streams low-level filesystem changes detected by FileWatchService.
         *     Events are emitted when task files are created, modified, or deleted on disk,
         *     including changes made externally (outside the API).
         *
         *     **Event Types:**
         *     - `file.created`: A .md file was created in a task directory
         *     - `file.modified`: A .md file was modified on disk
         *     - `file.deleted`: A .md file was deleted from disk
         *
         *     **Important Notes:**
         *     - May emit multiple events for a single logical operation (e.g., moving a task emits delete + create)
         *     - Includes external file changes (manual edits, git operations, etc.)
         *     - Lower-level than task events - one task operation may generate multiple file events
         *
         *     **Recommended for:** Monitoring tools, advanced synchronization, debugging
         *
         *     Connection stays open indefinitely. Clients should implement reconnection logic.
         */
        get: operations["subscribeToFileEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get backend configuration
         * @description Returns the current backend configuration as a read-only list of key-value pairs.
         *
         *     Useful for clients to adapt their behavior based on backend capabilities
         *     (e.g., show/hide terminal UI based on terminal.enabled setting).
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tasks
         * @description Retrieve a list of all tasks with optional filtering
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Create a new task
         * @description Create a new task with the provided details
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific task
         * @description Retrieve a task by its unique ID
         */
        get: operations["getTask"];
        /**
         * Update a task
         * @description Update an existing task (full replacement)
         */
        put: operations["updateTask"];
        post?: never;
        /**
         * Delete a task
         * @description Delete a task by its unique ID
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update task status
         * @description Move a task to a different status/column (planned, ongoing, done)
         */
        patch: operations["updateTaskStatus"];
        trace?: never;
    };
    "/tasks/{id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update task position
         * @description Update a task's position within its column, or move it to another column
         *     at a specific position. Automatically adjusts order of affected tasks.
         */
        patch: operations["updateTaskOrder"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Setting: {
            /**
             * @description Configuration key
             * @example terminal.enabled
             */
            key: string;
            /**
             * @description Configuration value
             * @example false
             */
            value: string;
            /**
             * @description Human-readable description of the setting
             * @example PTY terminal support enabled
             */
            description?: string;
        };
        SettingsResponse: {
            settings: components["schemas"]["Setting"][];
        };
        Task: {
            /**
             * Format: uuid
             * @description Unique identifier for the task
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Auto-generated monotonically increasing task number. Read-only, assigned at creation.
             * @example 42
             */
            readonly number: number;
            /**
             * @description Human-readable task title
             * @example Implement user authentication
             */
            title: string;
            /**
             * @description Task description in Markdown format
             * @example ## Description
             *
             *     Implement JWT-based authentication...
             *
             *     ## Acceptance Criteria
             *
             *     - [ ] Login endpoint
             *     - [ ] Token validation
             */
            description: string;
            status: components["schemas"]["TaskStatus"];
            /**
             * @description Position of task within its column (1-based). Lower numbers appear first. 1 = highest priority position.
             * @example 1
             */
            order: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of task creation
             * @example 2025-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of last update
             * @example 2025-01-15T14:22:00Z
             */
            updatedAt: string;
            /**
             * @description List of assignee usernames
             * @example [
             *       "alice",
             *       "bob"
             *     ]
             */
            assignees: string[];
            /**
             * @description List of category tags
             * @example [
             *       "feature",
             *       "backend"
             *     ]
             */
            categories: string[];
            priority: components["schemas"]["TaskPriority"];
        };
        TaskCreate: {
            /**
             * Format: uuid
             * @description Optional client-generated UUID for deduplicating SSE events. When provided, will be included in the emitted task.created event.
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientMutationId?: string;
            /**
             * @description Human-readable task title
             * @example Implement user authentication
             */
            title: string;
            /**
             * @description Task description in Markdown format
             * @example ## Description
             *
             *     Implement JWT-based authentication...
             */
            description: string;
            /** @default planned */
            status: components["schemas"]["TaskStatus"];
            /**
             * @description List of assignee usernames
             * @default []
             */
            assignees: string[];
            /**
             * @description List of category tags
             * @default []
             */
            categories: string[];
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
            /**
             * @description Position within the column (1-based)
             * @default 1
             */
            order: number;
        };
        TaskUpdate: {
            /**
             * Format: uuid
             * @description Optional client-generated UUID for deduplicating SSE events. When provided, will be included in the emitted task.updated event.
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientMutationId?: string;
            /** @description Human-readable task title */
            title: string;
            /** @description Task description in Markdown format */
            description: string;
            status?: components["schemas"]["TaskStatus"];
            /** @description List of assignee usernames */
            assignees?: string[];
            /** @description List of category tags */
            categories?: string[];
            priority?: components["schemas"]["TaskPriority"];
            /** @description Position within the column (1-based) */
            order?: number;
        };
        TaskStatusUpdate: {
            /**
             * Format: uuid
             * @description Optional client-generated UUID for deduplicating SSE events. When provided, will be included in the emitted task.updated event.
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientMutationId?: string;
            status: components["schemas"]["TaskStatus"];
        };
        TaskOrderUpdate: {
            /**
             * Format: uuid
             * @description Optional client-generated UUID for deduplicating SSE events. When provided, will be included in the emitted task.updated event(s).
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientMutationId?: string;
            /** @description Target position (1-based) */
            newOrder: number;
            /** @description Target column (if moving between columns) */
            newStatus?: components["schemas"]["TaskStatus"];
        };
        /**
         * @description Task status corresponding to board columns
         * @example planned
         * @enum {string}
         */
        TaskStatus: "planned" | "ongoing" | "done";
        /**
         * @description Task priority level
         * @example medium
         * @enum {string}
         */
        TaskPriority: "low" | "medium" | "high";
        Error: {
            /**
             * @description Error message
             * @example Task not found
             */
            message: string;
            /**
             * @description Error code for client handling
             * @example TASK_NOT_FOUND
             */
            code?: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
        TaskEvent: {
            /**
             * @description Type of task event emitted by TaskEventService:
             *     - `task.created`: New task was created
             *     - `task.updated`: Task was modified (any field changed)
             *     - `task.deleted`: Task was deleted
             * @example task.created
             * @enum {string}
             */
            eventType: "task.created" | "task.updated" | "task.deleted";
            /**
             * Format: uuid
             * @description UUID of the affected task
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            taskId: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the event occurred.
             *     Also used as SSE event ID for client reconnection.
             * @example 2025-01-15T10:30:00Z
             */
            timestamp: string;
            /**
             * Format: uuid
             * @description Client-generated UUID from the mutation request that caused this event.
             *     Present when the event was triggered by an API call that included a clientMutationId.
             *     Null for events triggered by external changes (manual file edits, file watch events).
             *     Clients can use this to identify and skip events they originated.
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            clientMutationId?: string | null;
            /**
             * @description Complete task object. For created/updated events, contains current state.
             *     For deleted events, contains the last known state before deletion.
             */
            task: components["schemas"]["Task"];
        };
        TaskCreatedEvent: Omit<components["schemas"]["TaskEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "task.created";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "task.created";
        };
        TaskUpdatedEvent: Omit<components["schemas"]["TaskEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "task.updated";
            /**
             * @description Object indicating which fields were modified. Each key corresponds
             *     to a task field, value is `true` if changed, omitted if unchanged.
             * @example {
             *       "status": true,
             *       "order": true
             *     }
             */
            changes: {
                /** @description Title was changed */
                title?: boolean;
                /** @description Description was changed */
                description?: boolean;
                /** @description Status was changed (task moved between columns) */
                status?: boolean;
                /** @description Assignees list was changed */
                assignees?: boolean;
                /** @description Categories list was changed */
                categories?: boolean;
                /** @description Priority was changed */
                priority?: boolean;
                /** @description Order within column was changed */
                order?: boolean;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "task.updated";
        };
        TaskDeletedEvent: Omit<components["schemas"]["TaskEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "task.deleted";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "task.deleted";
        };
        FileEvent: {
            /**
             * @description Type of file event emitted by FileEventService:
             *     - `file.created`: A .md file was created in the tasks directory
             *     - `file.modified`: A .md file was modified on disk
             *     - `file.deleted`: A .md file was deleted from disk
             * @example file.created
             * @enum {string}
             */
            eventType: "file.created" | "file.modified" | "file.deleted";
            /**
             * @description Absolute path to the affected file
             * @example /path/to/tasks/planned/example-task.md
             */
            path: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when the event occurred
             * @example 1705318200000
             */
            timestamp: number;
            /**
             * @description Task status directory (only present for created/deleted events)
             * @example planned
             * @enum {string}
             */
            directory?: "planned" | "ongoing" | "done";
        };
        FileCreatedEvent: Omit<components["schemas"]["FileEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "file.created";
            /** @enum {string} */
            directory: "planned" | "ongoing" | "done";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "file.created";
        };
        FileModifiedEvent: Omit<components["schemas"]["FileEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "file.modified";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "file.modified";
        };
        FileDeletedEvent: Omit<components["schemas"]["FileEvent"], "eventType"> & {
            /** @enum {string} */
            eventType?: "file.deleted";
            /** @enum {string} */
            directory: "planned" | "ongoing" | "done";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            eventType: "file.deleted";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    subscribeToTaskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TaskEvent"];
                };
            };
        };
    };
    subscribeToFileEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["FileEvent"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "settings": [
                     *         {
                     *           "key": "server.port",
                     *           "value": "8080",
                     *           "description": "Server port"
                     *         },
                     *         {
                     *           "key": "tasks.directory",
                     *           "value": "./tasks",
                     *           "description": "Tasks storage directory"
                     *         },
                     *         {
                     *           "key": "tasks.cacheEnabled",
                     *           "value": "true",
                     *           "description": "Task caching enabled"
                     *         },
                     *         {
                     *           "key": "terminal.enabled",
                     *           "value": "false",
                     *           "description": "PTY terminal support enabled"
                     *         },
                     *         {
                     *           "key": "terminal.idleTimeoutMinutes",
                     *           "value": "30",
                     *           "description": "Terminal idle timeout in minutes"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description Filter tasks by status */
                status?: components["schemas"]["TaskStatus"];
                /** @description Filter tasks by assignee */
                assignee?: string;
                /** @description Filter tasks by category */
                category?: string;
                /** @description Filter tasks by priority */
                priority?: components["schemas"]["TaskPriority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Task created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict (e.g., duplicate slug) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Task updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict (e.g., duplicate slug) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Task status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTaskOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskOrderUpdate"];
            };
        };
        responses: {
            /** @description Task positions updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description All tasks whose order was changed */
                        updated?: components["schemas"]["Task"][];
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
