/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tasks
         * @description Retrieve a list of all tasks with optional filtering
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Create a new task
         * @description Create a new task with the provided details
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific task
         * @description Retrieve a task by its unique ID
         */
        get: operations["getTask"];
        /**
         * Update a task
         * @description Update an existing task (full replacement)
         */
        put: operations["updateTask"];
        post?: never;
        /**
         * Delete a task
         * @description Delete a task by its unique ID
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update task status
         * @description Move a task to a different status/column (planned, ongoing, done)
         */
        patch: operations["updateTaskStatus"];
        trace?: never;
    };
    "/tasks/{id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update task position
         * @description Update a task's position within its column, or move it to another column
         *     at a specific position. Automatically adjusts order of affected tasks.
         */
        patch: operations["updateTaskOrder"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            /**
             * Format: uuid
             * @description Unique identifier for the task
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Human-readable task title
             * @example Implement user authentication
             */
            title: string;
            /**
             * @description Task description in Markdown format
             * @example ## Description
             *
             *     Implement JWT-based authentication...
             *
             *     ## Acceptance Criteria
             *
             *     - [ ] Login endpoint
             *     - [ ] Token validation
             */
            description: string;
            status: components["schemas"]["TaskStatus"];
            /**
             * @description Position of task within its column (1-based). Lower numbers appear first. 1 = highest priority position.
             * @example 1
             */
            order: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of task creation
             * @example 2025-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of last update
             * @example 2025-01-15T14:22:00Z
             */
            updatedAt: string;
            /**
             * @description List of assignee usernames
             * @example [
             *       "alice",
             *       "bob"
             *     ]
             */
            assignees: string[];
            /**
             * @description List of category tags
             * @example [
             *       "feature",
             *       "backend"
             *     ]
             */
            categories: string[];
            priority: components["schemas"]["TaskPriority"];
        };
        TaskCreate: {
            /**
             * @description Human-readable task title
             * @example Implement user authentication
             */
            title: string;
            /**
             * @description Task description in Markdown format
             * @example ## Description
             *
             *     Implement JWT-based authentication...
             */
            description: string;
            /** @default planned */
            status: components["schemas"]["TaskStatus"];
            /**
             * @description List of assignee usernames
             * @default []
             */
            assignees: string[];
            /**
             * @description List of category tags
             * @default []
             */
            categories: string[];
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
            /**
             * @description Position within the column (1-based)
             * @default 1
             */
            order: number;
        };
        TaskUpdate: {
            /** @description Human-readable task title */
            title: string;
            /** @description Task description in Markdown format */
            description: string;
            status?: components["schemas"]["TaskStatus"];
            /** @description List of assignee usernames */
            assignees?: string[];
            /** @description List of category tags */
            categories?: string[];
            priority?: components["schemas"]["TaskPriority"];
            /** @description Position within the column (1-based) */
            order?: number;
        };
        TaskStatusUpdate: {
            status: components["schemas"]["TaskStatus"];
        };
        TaskOrderUpdate: {
            /** @description Target position (1-based) */
            newOrder: number;
            /** @description Target column (if moving between columns) */
            newStatus?: components["schemas"]["TaskStatus"];
        };
        /**
         * @description Task status corresponding to board columns
         * @example planned
         * @enum {string}
         */
        TaskStatus: "planned" | "ongoing" | "done";
        /**
         * @description Task priority level
         * @example medium
         * @enum {string}
         */
        TaskPriority: "low" | "medium" | "high";
        Error: {
            /**
             * @description Error message
             * @example Task not found
             */
            message: string;
            /**
             * @description Error code for client handling
             * @example TASK_NOT_FOUND
             */
            code?: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTasks: {
        parameters: {
            query?: {
                /** @description Filter tasks by status */
                status?: components["schemas"]["TaskStatus"];
                /** @description Filter tasks by assignee */
                assignee?: string;
                /** @description Filter tasks by category */
                category?: string;
                /** @description Filter tasks by priority */
                priority?: components["schemas"]["TaskPriority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Task created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict (e.g., duplicate slug) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Task updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict (e.g., duplicate slug) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Task status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTaskOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskOrderUpdate"];
            };
        };
        responses: {
            /** @description Task positions updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description All tasks whose order was changed */
                        updated?: components["schemas"]["Task"][];
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
